title: 강부벌레
description: 나의 눈물만이 나를 이긴다.
theme: just-the-docs

url: https://tth-97.github.io/tth-97.github.io

math: mathjax


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
    G-19W80PS6YK
    
google_analytics:
  id: G-KH7KPG2T9N
